<a href="https://colab.research.google.com/github/Jakaria6284/Next_word_prediction_using_LSTM/blob/master/nextWordPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install keras

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
text="""It was a bright cold day in April, and the clocks were striking thirteen." Big Brother is watching you. War is peace. Freedom is slavery. Ignorance is strength. The past was erased, the erasure was forgotten, the lie became the truth. Doublethink means the power of holding two contradictory beliefs in one's mind simultaneously, and accepting both of them. If you want a picture of the future, imagine a boot stamping on a human face—forever. Nothing was your own except the few cubic centimeters inside your skull. We are the dead. Our only true life is in the future. Thoughtcrime does not entail death: thoughtcrime is death. To die hating them, that was freedom.

Reality exists in the human mind, and nowhere else. Freedom is the freedom to say that two plus two make four. Power is in tearing human minds to pieces and putting them together again in new shapes of your own choosing. The choice for mankind lies between freedom and happiness, and for the great bulk of mankind, happiness is better. Who controls the past controls the future. Who controls the present controls the past. The best books are those that tell you what you know already. Until they become conscious, they will never rebel, and until after they have rebelled, they cannot become conscious. It is not possible to found a civilization on fear and hatred and cruelty. It would never endure. Perhaps one did not want to be loved so much as to be understood. The object of power is power"""

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
tokenizer.word_index.items()

dict_items([('the', 1), ('is', 2), ('and', 3), ('in', 4), ('of', 5), ('to', 6), ('was', 7), ('a', 8), ('freedom', 9), ('you', 10), ('power', 11), ('controls', 12), ('they', 13), ('it', 14), ('past', 15), ('two', 16), ('them', 17), ('future', 18), ('human', 19), ('your', 20), ('not', 21), ('that', 22), ('mind', 23), ('want', 24), ('on', 25), ('own', 26), ('are', 27), ('thoughtcrime', 28), ('death', 29), ('for', 30), ('mankind', 31), ('happiness', 32), ('who', 33), ('until', 34), ('become', 35), ('conscious', 36), ('never', 37), ('be', 38), ('bright', 39), ('cold', 40), ('day', 41), ('april', 42), ('clocks', 43), ('were', 44), ('striking', 45), ('thirteen', 46), ('big', 47), ('brother', 48), ('watching', 49), ('war', 50), ('peace', 51), ('slavery', 52), ('ignorance', 53), ('strength', 54), ('erased', 55), ('erasure', 56), ('forgotten', 57), ('lie', 58), ('became', 59), ('truth', 60), ('doublethink', 61), ('means', 62), ('holding', 63), ('contradictory', 64), ('beliefs', 65), ("one's", 66

In [ ]:
input_sequences=[]
for line in text.split("."):
  word=tokenizer.texts_to_sequences([line.strip()])[0]
  for i in range(1,len(word)):
    n_gram_sequence=word[:i+1]
    input_sequences.append(n_gram_sequence)




In [ ]:
max_seq_length = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_seq_length, padding='pre')
input_sequences


array([[  0,   0,   0, ...,   0,  14,   7],
       [  0,   0,   0, ...,  14,   7,   8],
       [  0,   0,   0, ...,   7,   8,  39],
       ...,
       [  0,   0,   0, ..., 146,   5,  11],
       [  0,   0,   0, ...,   5,  11,   2],
       [  0,   0,   0, ...,  11,   2,  11]], dtype=int32)

In [ ]:
X,y=input_sequences[:,:-1],input_sequences[:,-1]
print(y)

[  7   8  39  40  41   4  42   3   1  43  44  45  46  48   2  49  10   2
  51   2  52   2  54  15   7  55   1  56   7  57   1  58  59   1  60  62
   1  11   5  63  16  64  65   4  66  23  67   3  68  69   5  17  10  24
   8  71   5   1  18  72   8  73  74  25   8  19  75   7  20  26  77   1
  78  79  80  81  20  82  27   1  84  86  87  88   2   4   1  18  89  21
  90  29  28   2  29  91  92  17  22   7   9  94   4   1  19  23   3  95
  96   2   1   9   6  97  22  16  98  16  99 100   2   4 101  19 102   6
 103   3 104  17 105 106   4 107 108   5  20  26 109 110  30  31 111 112
   9   3  32   3  30   1 113 114   5  31  32   2 115  12   1  15  12   1
  18  12   1 116  12   1  15 117 118  27 119  22 120  10 121  10 122 123
  13  35  36  13 124  37 125   3  34 126  13 127 128  13 129  35  36   2
  21 130   6 131   8 132  25 133   3 134   3 135 136  37 137 139 140  21
  24   6  38 141 142 143 144   6  38 145 146   5  11   2  11]


In [ ]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
model=Sequential(
   [
    Embedding(total_words,10,input_length=max_seq_length-1),
    LSTM(100,return_sequences=True),
    LSTM(100),
    Dense(100,activation="relu"),
    Dense(total_words,activation="softmax")
   ]
)

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=500,verbose=1)

Epoch 1/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - accuracy: 0.7339 - loss: 0.8001
Epoch 2/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8505 - loss: 0.5689
Epoch 3/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8555 - loss: 0.5638
Epoch 4/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8845 - loss: 0.5239
Epoch 5/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.9125 - loss: 0.4435
Epoch 6/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8933 - loss: 0.4292
Epoch 7/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 0.8999 - loss: 0.4613
Epoch 8/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8863 - loss: 0.4846
Epoch 9/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8951 - loss: 0.4590
Epoch 10/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9115 - loss: 0.4020
Epoch 11/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8917 - loss: 0.4661
Epoch 12/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9004 - lo

In [ ]:
loss, accuracy = model.evaluate(X, y)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9760 - loss: 0.0613
Test Accuracy: 96.97%


In [ ]:
def predict_next_word(model, tokenizer, text_seq, max_length):
    encoded = tokenizer.texts_to_sequences([text_seq])[0]
    encoded = pad_sequences([encoded], maxlen=max_length-1, padding='pre')
    predicted_index = np.argmax(model.predict(encoded), axis=-1)[0]

    for word, index in tokenizer.word_index.items():
        if index == predicted_index:
            return word
    return ""

# Test next word prediction
seed_text = "Reality exists in the"
predicted_word = predict_next_word(model, tokenizer, seed_text, max_seq_length)
print(f"Predicted next word: {predicted_word}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Predicted next word: human


In [ ]:
!pip install pyngrok nest_asyncio fastapi uvicorn tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.8 MB/s eta 0:00:00


In [ ]:
!pip install pyngrok
!ngrok authtoken 2rZN7l22mn8E4SndCTFZPfBdSo0_2B8DrLU2HrS2xLJ2ZsXjm


Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml


In [ ]:
import uvicorn
import nest_asyncio
from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from pyngrok import ngrok

# Apply nest_asyncio to allow FastAPI to run inside Colab
nest_asyncio.apply()

# Initialize FastAPI
app = FastAPI()

# Enable CORS for frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change to specific origins in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Your trained model and tokenizer should already exist in Colab
# model and tokenizer are assumed to be defined in the Colab environment

# Maximum sequence length used in training
max_seq_length = max_seq_length  # Adjust based on your training setup

# Function to predict the next word
def predict_next_word(text_seq):
    encoded = tokenizer.texts_to_sequences([text_seq])[0]
    encoded = pad_sequences([encoded], maxlen=max_seq_length-1, padding='pre')
    predicted_index = np.argmax(model.predict(encoded), axis=-1)[0]

    for word, index in tokenizer.word_index.items():
        if index == predicted_index:
            return word
    return ""

# FastAPI endpoint for next word prediction
@app.get("/predict/")
def get_prediction(text: str = Query(..., description="Input text sequence")):
    predicted_word = predict_next_word(text)
    return {"input": text, "predicted_word": predicted_word}

# Expose API using ngrok
port = 8000
public_url = ngrok.connect(port).public_url
print(f"Public API URL: {public_url}")

# Run the FastAPI server
uvicorn.run(app, host="0.0.0.0", port=port)


INFO:     Started server process [1641]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)


Public API URL: https://f2e7-34-106-73-104.ngrok-free.app
INFO:     103.88.141.62:0 - "OPTIONS /predict/?text=Reality%20exists%20in%20the HTTP/1.1" 200 OK
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
INFO:     103.88.141.62:0 - "GET /predict/?text=Reality%20exists%20in%20the HTTP/1.1" 200 OK
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
INFO:     103.88.141.62:0 - "GET /predict/?text=Reality%20exists%20in%20the HTTP/1.1" 200 OK
INFO:     103.88.141.62:0 - "OPTIONS /predict/?text=Freedom%20is%20the%20freedom HTTP/1.1" 200 OK
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
INFO:     103.88.141.62:0 - "GET /predict/?text=Freedom%20is%20the%20freedom HTTP/1.1" 200 OK
INFO:     103.88.141.62:0 - "OPTIONS /predict/?text=%20Who%20controls%20the%20past%20controls%20the%20future. HTTP/1.1" 200 OK
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
INFO:     103.88.141.62:0 - "GET /predict/?text=%20Who%20controls%20the%20past%20controls%20the%20future. HTTP/1.1" 200 OK
INFO:     103.88.141.62:0 - "OPTIONS /predict/?text=Who%20control